### PR TITLE
added refreshToken code in Client prototype

### PR DESCRIPTION
**Pull request by aymather**
Sorry this is the first time I've ever made a pull request, sorry if I'm doing something wrong <3

### CODE REVIEW

**Comment by MarcGodard** [comment]
Good job, can you add a test to cover this?

**Comment by samuelmr** [comment]
Thanks, I merged the pull request.

Your file test/refreshTokenTest.js was empty. Did you write a test that you didn't commit or that wasn't for some reason included in the pull request?

**Comment by aymather** [comment]
I apologize, while I was testing this, the refresh was not working for
some reason when I used it inside your package. I was working on creating a
test scenario.

Sorry I should have done more checking before making the pull request <3

**Comment by samuelmr** [comment]
Do you mean that now token refresh works for you even without your modification?

(I thought it should since I've been using the client on a regular basis for years...)

**Comment by aymather** [comment]
Yes I can refresh a token without the modification to the package that I
suggested. I just thought it would be convenient to build it into the class
that you created. For some reason the post request just isn't working
though so I'm still just trying to figure it out.

**Comment by MarcGodard** [comment]
Should we revert this merge until it is ready?

**Comment by aymather** [comment]
Yes, so sorry!

**Pull request merged**
